### PR TITLE
fix: multiple decimal points

### LINKED ISSUE #150: Can enter invalid characters into auction and buy now creation value

### PR DESCRIPTION
**Pull request by creativogee**
## Description
closes #150

### CODE REVIEW

File: src/features/partials/SellAsset/index.tsx [hunk 1]
```diff
@@ -59,17 +59,13 @@ const SellAsset = ({ asset }: { asset: AssetWithListing | undefined }) => {
 
   const dispatch = useAppDispatch()
 
-  const validate = ({ price, endDate }: { price: string; endDate: Date }) => {
+  const validate = ({ price, endDate }: { price: number; endDate: Date }) => {
```
Comment (jmulq) [inline src/features/partials/SellAsset/index.tsx:62]: Would it be better to just not allow them to type invalid characters in?

Comment (jmulq) [reply src/features/partials/SellAsset/index.tsx:62]: Okay awesome

**Review by jmulq — APPROVED** [review]

File: src/features/partials/SellAsset/index.tsx [hunk 2]
```diff
@@ -175,10 +171,10 @@ const SellAsset = ({ asset }: { asset: AssetWithListing | undefined }) => {
               <Formik
                 initialValues={
                   {
-                    price: '',
+                    price: '' as unknown,
```
Comment (jmulq) [inline src/features/partials/SellAsset/index.tsx:174]: Why the unknown type?

**Review by jmulq — APPROVED** [review]
lgtm - one comment about the unknown type

File: src/features/partials/SellAsset/index.tsx (hunk 2 above)
Comment (creativogee) [reply src/features/partials/SellAsset/index.tsx:174]: typescript is expecting a number as the initial value, without the unknown alias, it will not allow the initial value to be empty string. We need it to be empty string so that the input field is empty else would have been forced to set an initial price value of 0 which is a number.
